package com.example.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.group_id
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq_id
     *
     * @mbg.generated
     */
    private String qqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gold_coin
     *
     * @mbg.generated
     */
    private String goldCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sign_in
     *
     * @mbg.generated
     */
    private String signIn;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public User(Integer id, String groupId, String qqId, String goldCoin, String signIn) {
        this.id = id;
        this.groupId = groupId;
        this.qqId = qqId;
        this.goldCoin = goldCoin;
        this.signIn = signIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.group_id
     *
     * @return the value of user.group_id
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.group_id
     *
     * @param groupId the value for user.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq_id
     *
     * @return the value of user.qq_id
     *
     * @mbg.generated
     */
    public String getQqId() {
        return qqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq_id
     *
     * @param qqId the value for user.qq_id
     *
     * @mbg.generated
     */
    public void setQqId(String qqId) {
        this.qqId = qqId == null ? null : qqId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gold_coin
     *
     * @return the value of user.gold_coin
     *
     * @mbg.generated
     */
    public String getGoldCoin() {
        return goldCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gold_coin
     *
     * @param goldCoin the value for user.gold_coin
     *
     * @mbg.generated
     */
    public void setGoldCoin(String goldCoin) {
        this.goldCoin = goldCoin == null ? null : goldCoin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sign_in
     *
     * @return the value of user.sign_in
     *
     * @mbg.generated
     */
    public String getSignIn() {
        return signIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sign_in
     *
     * @param signIn the value for user.sign_in
     *
     * @mbg.generated
     */
    public void setSignIn(String signIn) {
        this.signIn = signIn == null ? null : signIn.trim();
    }
}